# Generated by Django 6.1 on 2026-08-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('condition', 'Condition'), ('http', 'HTTP Request'), ('telegram', 'Telegram'), ('transform', 'JSON Transform')], max_length=20),
        ),
    ]
