# Generated by Django 6.1 on 2026-08-18 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        ('workflows', '0002_alter_workflownode_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='default_on_error',
            field=models.CharField(choices=[('stop', 'Stop'), ('retry', 'Retry'), ('continue', 'Continue')], default='stop', max_length=10),
        ),
        migrations.AddField(
            model_name='workflow',
            name='notify_after_consecutive',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='workflow',
            name='notify_on_failure',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='notify_telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workflow',
            name='notify_telegram_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='connections.connection'),
        ),
        migrations.CreateModel(
            name='WorkflowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('minutes', 'каждые N минут'), ('hours', 'каждые N часов'), ('daily', 'каждый день в определённое время'), ('days', 'каждый N-й день'), ('cron', 'cron-выражение')], default='minutes', max_length=10)),
                ('interval', models.PositiveIntegerField(default=30)),
                ('daily_time', models.TimeField(blank=True, null=True)),
                ('cron_expression', models.CharField(blank=True, default='', max_length=100)),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('name_snapshot', models.CharField(max_length=255)),
                ('description_snapshot', models.TextField(blank=True, default='')),
                ('nodes_snapshot', models.JSONField(blank=True, default=list)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'version'), name='unique_workflow_version')],
            },
        ),
    ]
