# Generated by Django 6.1 on 2026-08-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeexecution',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nodeexecution',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nodeexecution',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='trigger',
            field=models.CharField(choices=[('webhook', 'webhook'), ('test', 'test'), ('schedule', 'schedule'), ('replay', 'replay'), ('manual', 'manual')], default='webhook', max_length=10),
        ),
        migrations.AlterField(
            model_name='nodeexecution',
            name='status',
            field=models.CharField(choices=[('running', 'RUNNING'), ('retrying', 'RETRYING'), ('success', 'SUCCESS'), ('failed', 'FAILED'), ('skipped', 'SKIPPED')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('queued', 'QUEUED'), ('running', 'RUNNING'), ('retrying', 'RETRYING'), ('success', 'SUCCESS'), ('failed', 'FAILED'), ('cancelled', 'CANCELLED')], default='queued', max_length=10),
        ),
    ]
